# Lasso and Ridge Regression

In [39]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from sklearn.linear_model import LinearRegression

In [40]:
df = pd.read_csv("/content/50_Startups.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   RDSpend         48 non-null     float64
 1   Administration  50 non-null     float64
 2   MarketingSpend  47 non-null     float64
 3   State           50 non-null     object 
 4   Profit          50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [41]:
df.head()

RDSpend  Administration  MarketingSpend       State     Profit
0  165349.20       136897.80       471784.10    New York  192261.83
1  162597.70       151377.59       443898.53  California  191792.06
2  153441.51       101145.55       407934.54     Florida  191050.39
3  144372.41       118671.85       383199.62    New York  182901.99
4  142107.34        91391.77       366168.42     Florida  166187.94

In [42]:
df.isna().sum()

RDSpend           2
Administration    0
MarketingSpend    3
State             0
Profit            0
dtype: int64

In [43]:
df.dropna(inplace=True)

In [44]:
X_numerical = df[['RDSpend', 'Administration', 'MarketingSpend']]
X_state = pd.get_dummies(df['State'], drop_first=True, dtype=int)

x = pd.concat([X_numerical, X_state], axis=1).values
y = df.iloc[:,[-1]].values

print(x.shape,y.shape)

(46, 5) (46, 1)


In [45]:
from sklearn.linear_model import LassoCV, RidgeCV, ElasticNetCV


In [46]:
from sklearn.model_selection import train_test_split


In [47]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2,random_state=90)

In [48]:
model = LassoCV()
model.fit(xtrain,ytrain).score(xtest,ytest)
# .score internally calls predict and r2_score methods

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:1664: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.9586209396191909

In [49]:
model.coef_

array([ 0.69871524, -0.        ,  0.04309662, -0.        , -0.        ])

In [50]:
model2 = RidgeCV()
model2.fit(xtrain,ytrain)
print(model2.score(xtest,ytest))
np.set_printoptions(suppress=True)
model2.coef_

0.9704845732183198


array([   0.75202098,   -0.05201325,    0.03073466, -349.65115058,
       -313.2209514 ])

In [51]:
model3 = ElasticNetCV()
model3.fit(xtrain,ytrain).score(xtest,ytest)


/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:1664: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.9621546829046009

In [52]:
model3.coef_

array([ 0.71353115, -0.016685  ,  0.04071336, -0.        , -0.        ])

ElasticNet : Linear Regression + Lasso + Ridge as regularizer

CV menas crossfold validation

In [53]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2,random_state=100)



In [58]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score

In [61]:
model = LinearRegression()
accuracy = cross_val_score(model,xtrain,ytrain,cv=5)
print(accuracy)
print("Average training Accuracy ",np.mean(accuracy).round(2),
      ' with SD of : ', np.std(accuracy).round(2) )

[0.97740783 0.9422405  0.86713994 0.89203518 0.91787763]
Average training Accuracy  0.92  with SD of :  0.04


In [67]:
from sklearn.metrics import r2_score
model.fit(xtrain,ytrain)
round(r2_score(ytest,model.predict(xtest)),2)

0.96

In [ ]:
# We got 96% accuracy in LinearRegression
# just by removing na values using These Regressions.