In [25]:
import numpy as np

In [26]:
# user defined or custom word embedding
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [27]:
#define data
train_data= ['Well done','Good Work','Great effort','Nice Work','Excellent','Weak','Poor effort','Not good','Very Very Bad']
train_label= [1,1,1,1,1,0,0,0,0]

In [28]:
# Embedding layer must be first layer

In [29]:
max_len = 0
my_data=set()
for w in train_data:
  s=w.split()
  if len(s) > max_len:
    max_len = len(s)
  for w in s:
    my_data.add(w.lower())

print(max_len)
print(my_data)


3
{'great', 'not', 'work', 'good', 'bad', 'weak', 'excellent', 'well', 'poor', 'done', 'nice', 'very', 'effort'}


In [30]:
num_tokens = len(my_data) + 1  # token starts from 0
print(num_tokens)

14


In [31]:
input_words=sorted(list(my_data))
input_words_dict={w:i+1 for i,w in enumerate(my_data)}


In [32]:
enocded_input_data=np.zeros((len(train_data),max_len))
for i in range(len(train_data)):
  for pos , w in enumerate(train_data[i].split()):
    enocded_input_data[i,pos]=input_words_dict[w.lower()]

In [33]:
enocded_input_data

array([[ 8., 10.,  0.],
       [ 4.,  3.,  0.],
       [ 1., 13.,  0.],
       [11.,  3.,  0.],
       [ 7.,  0.,  0.],
       [ 6.,  0.,  0.],
       [ 9., 13.,  0.],
       [ 2.,  4.,  0.],
       [12., 12.,  5.]])

In [34]:
from tensorflow.keras.layers import Embedding, Input, LSTM, Dense, Flatten

from tensorflow.keras.models import Sequential


In [35]:
model = Sequential()
dim = 512
model.add(Input(shape=(4,)))
model.add(Embedding(num_tokens, dim))

model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])

model.summary()


Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ (None, 4, 512)         │         7,168 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_5 (Flatten)             │ (None, 2048)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │         2,049 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9,217 (36.00 KB)

 Trainable params: 9,217 (36.00 KB)

 Non-trainable params: 0 (0.00 B)

In [36]:
model.fit(enocded_input_data, train_label, epochs=25)

ValueError: Unrecognized data type: x=[[ 8. 10.  0.]
 [ 4.  3.  0.]
 [ 1. 13.  0.]
 [11.  3.  0.]
 [ 7.  0.  0.]
 [ 6.  0.  0.]
 [ 9. 13.  0.]
 [ 2.  4.  0.]
 [12. 12.  5.]] (of type <class 'numpy.ndarray'>)